[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/students/:id"
  to = "/.netlify/functions/students-id?id=:id"
  status = 200

[[redirects]]
  from = "/.netlify/functions/courses/:id"
  to = "/.netlify/functions/courses-id?id=:id"
  status = 200

[[redirects]]
  from = "/.netlify/functions/teachers/:id"
  to = "/.netlify/functions/teachers-id?id=:id"
  status = 200

